import type { GameLevel } from "@/components/escape-room/types";

export const officialGameLevels: GameLevel[] = [
  {
    id: "official-01",
    slug: "escape-room",
    stageSlug: "library",
    title: "Stage 01",
    subtitle: "Midnight Library Escape",
    difficulty: "Campus Puzzle",
    duration: "6-10 min",
    status: "live",
    mission: "Read the closing board, pull the cart lead, recover the desk key, verify the PA order, and unlock the library exit.",
    reward: "+50 XP · Midnight Reader",
    href: "/games/escape-room/library",
    accent: "from-[#7cbcff] via-[#4b7dff] to-[#9ed8ff]",
    cover: "/quests/escape-room/scenes/library-briefing.png",
  },
  {
    id: "official-02",
    slug: "dorm-lockout",
    stageSlug: "dorm",
    title: "Stage 02",
    subtitle: "Dorm Lounge Lockout",
    difficulty: "Residence Puzzle",
    duration: "7-11 min",
    status: "live",
    mission: "Read the dorm notices, trace the right unit, recover the returned passcard, and unlock the hallway exit.",
    reward: "+60 XP · Night Owl Resident",
    href: "/games/dorm-lockout",
    accent: "from-[#8fd2ff] via-[#4f86ff] to-[#b7e6ff]",
    cover: "/quests/escape-room/scenes/dorm-briefing.png",
  },
  {
    id: "official-03",
    slug: "last-train-escape",
    stageSlug: "station",
    title: "Stage 03",
    subtitle: "Last Train Escape",
    difficulty: "Transit Puzzle",
    duration: "8-12 min",
    status: "live",
    mission: "Read the route board, print the reissue slip, search the right bench bag, and clear the station gate before the last shuttle leaves.",
    reward: "+70 XP · Last Train Rider",
    href: "/games/last-train-escape",
    accent: "from-[#90c4ff] via-[#436dff] to-[#7dd8ff]",
    cover: "/quests/escape-room/scenes/station-briefing.png",
  },
];
