import type { GameLevel } from "@/components/escape-room/types";

export const officialGameLevels: GameLevel[] = [
  {
    id: "official-01",
    slug: "escape-room",
    title: "Official Stage 01",
    subtitle: "Midnight Library Escape",
    difficulty: "Campus Puzzle",
    duration: "6-10 min",
    status: "live",
    mission: "Read the closing board, pull the cart lead, recover the desk key, verify the PA order, and unlock the library exit.",
    reward: "+50 XP · Midnight Reader",
    href: "/games/escape-room",
    accent: "from-[#19d3c5] via-[#2c8cff] to-[#ffd166]",
    cover: "/quests/escape-room/library.png",
  },
  {
    id: "official-02",
    slug: "dorm-lockout",
    title: "Official Stage 02",
    subtitle: "Dorm Lounge Lockout",
    difficulty: "Residence Puzzle",
    duration: "7-11 min",
    status: "live",
    mission: "Read the dorm notices, trace the right unit, recover the returned passcard, and unlock the hallway exit.",
    reward: "+60 XP · Night Owl Resident",
    href: "/games/dorm-lockout",
    accent: "from-[#67e8f9] via-[#0f766e] to-[#bef264]",
    cover: "/quests/escape-room/dorm.png",
  },
  {
    id: "official-03",
    slug: "last-train-escape",
    title: "Official Stage 03",
    subtitle: "Last Train Escape",
    difficulty: "Transit Puzzle",
    duration: "8-12 min",
    status: "live",
    mission: "Read the route board, print the reissue slip, search the right bench bag, and clear the station gate before the last shuttle leaves.",
    reward: "+70 XP · Last Train Rider",
    href: "/games/last-train-escape",
    accent: "from-[#f59e0b] via-[#ef4444] to-[#fb7185]",
    cover: "/quests/escape-room/station.png",
  },
];
