import type { GameLevel } from "@/components/escape-room/types";

export const officialGameLevels: GameLevel[] = [
  {
    id: "official-01",
    slug: "escape-room",
    title: "Official Stage 01",
    subtitle: "Midnight Library Escape",
    difficulty: "Starter Puzzle",
    duration: "6-10 min",
    status: "live",
    mission: "Collect the shelf number and closing time, solve the broadcast, ask politely, and unlock the library exit.",
    reward: "+50 XP · Midnight Reader",
    href: "/games/escape-room",
    accent: "from-[#19d3c5] via-[#2c8cff] to-[#ffd166]",
    cover: "/quests/escape-room/stage-cover-library.svg",
  },
  {
    id: "official-02",
    slug: "library-vault",
    title: "Official Stage 02",
    subtitle: "Library Vault",
    difficulty: "Coming Soon",
    duration: "8-12 min",
    status: "locked",
    mission: "Decode archive labels and navigate an academic citation lock.",
    reward: "Preview only",
    accent: "from-[#67e8f9] via-[#0f766e] to-[#bef264]",
    cover: "/quests/escape-room/stage-cover-library.svg",
  },
  {
    id: "official-03",
    slug: "conference-rush",
    title: "Official Stage 03",
    subtitle: "Conference Rush",
    difficulty: "Coming Soon",
    duration: "10-14 min",
    status: "locked",
    mission: "Rebuild a presentation schedule before the keynote timer expires.",
    reward: "Preview only",
    accent: "from-[#f59e0b] via-[#ef4444] to-[#fb7185]",
    cover: "/quests/escape-room/stage-cover-conference.svg",
  },
];
